### ISSUE TITLE
Newtonsoft.Json

### ISSUE THREAD

**Issue by codesignist** [techartorg/MXSPyCOM#15]
MXSPyCOM was working correctly but then suddenly it gave this error:
"An assembly specified in the application dependencies manifest (MXSPyCOM.deps.json) was not found"

![image](https://user-images.githubusercontent.com/1472881/71539574-52692880-294f-11ea-91e6-bf8ce94f40f8.png)

Do you have any ideas?

**Comment by codesignist** [comment]
@JeffHanna can you help me?

**Comment by JeffHanna** [comment]
Do you happen to know which release you are using? NewtonsoftJSON has not been a dependency of MXSPyCOM since it switched to being build on .NET Core 3.0 - back in November of 2019.

I'd suggest getting the latest 1.12 release (https://github.com/techartorg/MXSPyCOM/releases/tag/1.12) and trying that.

**Comment by codesignist** [comment]
I've tried both 2.7 and 3.0 versions. I'm not sure which version gave this error.

I've cleaned AppData and problem solved.
Thank you.
